SubscriptionID     = "9ssddd-eervv"
TenantID           = "aaab12"
ResourceGroupName  = "Azure_SQL_01"
StorageAccountName = "sqlupworkjana01"
Location           = "Southeast Asia"
ContainerName      = "sqlbackup-1"